### ISSUE TITLE
GBL ... what and where is it?

### ISSUE THREAD

**Issue by whit2333** [AIDASoft/aidaTT#6]
CMake cannot find GBL. Where is it?

**Comment by petricm** [comment]
https://svnsrv.desy.de/websvn/wsvn/General.GeneralBrokenLines?

**Comment by whit2333** [comment]
Thanks!
It is hard to go from GBL to General Broken Lines even with google's help. For future reference the website appears to be
https://www.wiki.terascale.de/index.php/GeneralBrokenLines
